import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';

import NavBar from '../components/layout/NavBar';
import Footer from '../components/layout/Footer';

const Dashboard: NextPage = () => {
    return (
        <div className={styles.container}>
            <NavBar></NavBar>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Dashboard page
                </h1>
            </main>

            <Footer />
        </div>
    );
};

export default Dashboard;
