[features]
seeds = false
skip-lint = false

[programs.localnet]
soled = "927s7hwrsmMG62c7U5iRCxJyJrXf5sgrz94tUTLeDbCe"

[programs.devnet]
soled = "927s7hwrsmMG62c7U5iRCxJyJrXf5sgrz94tUTLeDbCe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/stellaw/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
