[features]
seeds = false
skip-lint = false
[programs.localnet]
soled = "Hen1HiTHovdX68H4PVBPTGfww6FGL3zgXTeboBZB7EwW"

[programs.devnet]
soled = "Hen1HiTHovdX68H4PVBPTGfww6FGL3zgXTeboBZB7EwW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
